LearningLog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Users/', include(('Users.urls', 'Users'), namespace='Users')),
    url(r'', include(('LearningLogs.urls', 'LearningLogs'), namespace='LearningLogs')),

]

LearningLogs/urls.py
# urls of app

from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', view=views.index, name='index'),

    # Page with topics
    url(r'^topics/$', view=views.topics, name='topics'),

    # Page for single topic
    url(r'^topics/(?P<topic_id>\d+)/$', view=views.topic, name='topic'),

    # Page for adding topic
    url(r'^new_topic/$', view=views.new_topic, name='new_topic'),

    # Page for adding entry for topic
    url(r'^new_entry/(?P<topic_id>\d+)/$', view=views.new_entry, name='new_entry'),

    # Page for editing entries
    url(r'^edit_entry/(?P<entry_id>\d+)/$', view=views.edit_entry, name='edit_entry'),

]

Users/urls.py
"""Defining urls templates for User app"""

from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views


urlpatterns = [
    # Login page
    url(r'^login/$', LoginView.as_view(template_name='Users/login.html'), name='login'),
    url(r'^logout$', view=views.logout_view, name='logout'),
    url(r'^register/$', view=views.register, name='register')
]

LearningLogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):
    text = models.CharField(max_length=50)
    posted_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    posted_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'


class Test(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return "Test object"

Users/models.py
from django.db import models

# Create your models here.

LearningLogs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': 'Name'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

LearningLogs/views.py
from django.shortcuts import render
from .models import Topic, Entry, Test
from .forms import TopicForm, EntryForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    """Displays home page"""
    return render(request, 'LearningLogs/index.html')


@login_required
def topics(request):
    """Displays page with topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('posted_date')
    context = {'topics': topics}
    return render(request, 'LearningLogs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Displays single topic and conected entries"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-posted_date')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'LearningLogs/topic.html', context)


@login_required
def new_topic(request):
    """Creates form for new topic, or import new topic to database"""
    if request.method != 'POST':
        # No data has been given so new form has to be created.
        form = TopicForm()
    else:
        # Data has been given as POST request, it has to be processed
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('LearningLogs:topics'))
    context = {'form': form}
    return render(request, 'LearningLogs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Creates form for new entry connected with topic -> topic_id"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('LearningLogs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'LearningLogs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Editing form"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LearningLogs:topic', args=[topic.id]))
    context = {'topic': topic, 'entry': entry, 'form': form}
    return render(request, 'LearningLogs/edit_entry.html', context)

Users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
# Create your views here.


def logout_view(request):
    """ Logout function """
    logout(request)
    return HttpResponseRedirect(reverse('LearningLogs:index'))


def register(request):
    """Displays a register page, where user can create an account"""
    if request.method != 'POST':
        form = UserCreationForm()

    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('LearningLogs:index'))
    context = {'form': form}
    return render(request, 'Users/register.html', context)

LearningLogs/templates/LearningLogs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LearningLog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <!--Static navBar-->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'LearningLogs:index' %}">Learning Log</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'LearningLogs:topics' %}">Topics</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'Users:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'Users:register' %}">Register</a></li>
                        <li><a href="{% url 'Users:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!--./nav-collapse -->
        </div>

    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

LearningLogs/templates/LearningLogs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit entry</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}
    {% block content %}
        <p>
            <a href="{% url 'LearningLogs:topic' topic.id %}">{{ topic }}</a>
        </p>

        <p>Entry editing</p>

        <form action="{% url 'LearningLogs:edit_entry' entry.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Save</button>
        </form>

    {% endblock %}
</body>
</html>

LearningLogs/templates/LearningLogs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WebApp</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %} <!-- Inherited block -->

    {% block header %}
        <div class="jumbotron">
            <h1 align="center">Monitor your learning progression</h1>
        </div>
    {% endblock %}

    {% block content %}
        <h2>
        <a href="{% url 'Users:register' %}">Register,</a> to start using the LearningLog application and store
        a list of information about new experiences.
        </h2>
        <h2>
          Post a new topic as soon as you catch up some new skills. Write about it, and come back to remind, whenever you want!
        </h2>
    {% endblock %}

</body>
</html>

LearningLogs/templates/LearningLogs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New entry</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}
    {% block content %}
        <p>
            <a href="{% url 'LearningLogs:topic' topic.id %}"></a>
        </p>

        <p>Add new entry:</p>
        <form action="{% url 'LearningLogs:new_entry' topic.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Post</button>
        </form>
    {% endblock %}
</body>
</html>

LearningLogs/templates/LearningLogs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Topic</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>Add a new topic:</h2>
    {% endblock %}
    {% block content %}
        <form action="{% url 'LearningLogs:new_topic' %}" method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
          <button name="submit">Add topic</button>
          {% endbuttons %}

        </form>
    {% endblock %}
</body>
</html>

LearningLogs/templates/LearningLogs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}

    {% block header %}
        <h2>{{ topic }}</h2>
    {% endblock %}

    {% block content %}
        <p>
            <a href="{% url 'LearningLogs:new_entry' topic.id %}">Add new entry</a>
        </p>
        <ul>
        {% for entry in entries %}
            <div class="panel panel-default">
               <div class="panel-heading">
                   <h3>
                       {{ entry.posted_date|date:'d M Y H:i' }}
                       <small>
                           <a href="{% url 'LearningLogs:edit_entry' entry.id %}">Edit</a>
                       </small>
                   </h3>
               </div>
                <div class="panel-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div>
        {% empty %}
            <li>No entries added yet.</li>
        {% endfor %}
        </ul>
    {% endblock content%}
</body>
</html>

LearningLogs/templates/LearningLogs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}

    {% block header %}
        <h2>Topics</h2>
    {% endblock %}

    {% block content %}

        <ul>
           {% for topic in topics %}
               <li><h3><a href="{% url 'LearningLogs:topic' topic.id %}">{{ topic }}</a></h3></li>
           {% empty %}
               <li>No topics added yet</li>
           {% endfor %}

        </ul>
        <h3><a href="{% url 'LearningLogs:new_topic' %}">Add new topic</a></h3>
    {% endblock %}content %}

</body>
</html>

Users/templates/Users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>Login to your account</h2>
    {% endblock %}

    {% block content %}
        {% if form.errors %}
            <p>Wrong username or password.</p>
        {% endif %}

        <form method="post" action="{% url 'Users:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Login</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'LearningLogs:index' %}"/>
        </form>

    {% endblock %}
</body>
</html>

Users/templates/Users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    {% extends 'LearningLogs/base.html' %}
    {% block content %}

        <form method="post" action="{% url 'Users:register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Register</button>
            <input type="hidden" name="next" value="{% url 'LearningLogs:index' %}"/>
        </form>
    {% endblock %}
</body>
</html>